<?php         
define("IKODES_LICENSE_TEXT_CONNECTION_FAILED", 'The server is currently unavailable. Please try again later.');
define("IKODES_LICENSE_TEXT_INVALID_RESPONSE", 'Received an invalid response from the server. Please contact support for assistance.');
define("IKODES_LICENSE_TEXT_VERIFIED_RESPONSE", 'Verification successful! Thank you for your purchase.');
define("IKODES_LICENSE_TEXT_PREPARING_MAIN_DOWNLOAD", 'Initializing the download of the main update...');
define("IKODES_LICENSE_TEXT_MAIN_UPDATE_SIZE", 'Main update file size:');
define("IKODES_LICENSE_TEXT_DONT_REFRESH", '(Do not refresh this page during the process.)');
define("IKODES_LICENSE_TEXT_DOWNLOADING_MAIN", 'Downloading the main update files...');
define("IKODES_LICENSE_TEXT_UPDATE_PERIOD_EXPIRED", 'Your update period has expired, or your license is invalid. Please reach out to support.');
define("IKODES_LICENSE_TEXT_UPDATE_PATH_ERROR", 'The update folder lacks the necessary write permissions, or the file path could not be determined. Contact support for help.');
define("IKODES_LICENSE_TEXT_MAIN_UPDATE_DONE", 'Main update files have been successfully downloaded and extracted.');
define("IKODES_LICENSE_TEXT_UPDATE_EXTRACTION_ERROR", 'Failed to extract the update zip file.');
define("IKODES_LICENSE_TEXT_PREPARING_SQL_DOWNLOAD", 'Getting ready to download the SQL update...');
define("IKODES_LICENSE_TEXT_SQL_UPDATE_SIZE", 'SQL update file size:');
define("IKODES_LICENSE_TEXT_DOWNLOADING_SQL", 'Downloading SQL update files...');
define("IKODES_LICENSE_TEXT_SQL_UPDATE_DONE", 'SQL update files have been successfully downloaded.');
define("IKODES_LICENSE_TEXT_UPDATE_WITH_SQL_IMPORT_FAILED", 'The application was updated successfully, but automatic SQL import failed. Please manually import the downloaded SQL file into your database.');
define("IKODES_LICENSE_TEXT_UPDATE_WITH_SQL_IMPORT_DONE", 'The application was successfully updated, and the SQL file was automatically imported.');
define("IKODES_LICENSE_TEXT_UPDATE_WITH_SQL_DONE", 'The application has been updated. Please manually import the downloaded SQL file into your database.');
define("IKODES_LICENSE_TEXT_UPDATE_WITHOUT_SQL_DONE", 'The application was updated successfully. No SQL updates were required.');
